### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by minsad79** [GuillaumeWaignier/fibaro#1]
Hello GuillaumeWaignier

I found your awesome solution

Consolidated Nest Account

Cheered for the cool operation

4 nests

Individual operation does not work

Can you reveal your fantastic solution?

**Comment by GuillaumeWaignier** [comment]
Hello,

You can now use the Nest quickapp that handle several nest devices (only HVAC system heat).

https://github.com/GuillaumeWaignier/fibaro/tree/master/quickApp/Nest
