### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by techbliss** [GuillaumeWaignier/fibaro#2]
Hi
are you planning to add a license to your quickapp.
I have nest cameras and thought of reusing some of your code.
great work by the way.

**Comment by GuillaumeWaignier** [comment]
Hi
I plan to use Apache 2.0 licence.
Thus you can reuse some part of the code.

For the nest cameras, you need to use the Google pubsub events (There are no REST API).
How do you do this in Lua ? (I have also nest cameras...)

Thanks

**Comment by techbliss** [comment]
hello
i was thinking to use the web url https://developers.nest.com/reference/api-camera#web_url
and embed them into html in labels.
her a example of a snapshot and live cam in labels.
the code i wanna reuse  is of your auth and varibles to logon.
to test make labels id la6 , la7 , la8


    self:updateView("la6", "text", '<img src="https://www.vegvesen.no/public/webkamera/kamera?id=640748" alt="E18 Lakseberget" class="webkamera-bilde">')
    self:updateView("la7", "text", '<img id="image0" src="http://77.243.103.105:8081/mjpg/video.mjpg" class="img-responsive img-rounded detailimage" alt="" title="Click here to enter the camera located in Russian Federation, region Moscow City, Nekrasovka">')
    self:updateView("la8", "text", '<video width="620" controls poster="https://upload.wikimedia.org/wikipedia/commons/e/e8/lephants_Dream_s5_both.jpg"><source src="https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4" type="video/mp4"> <source src="https://archive.org/download/lephantsDream/ed_hd.ogv" type="video/ogg"> <source src="https://archive.org/download/ElephantsDream/ed_hd.avi" type="video/avi">Your browser doesn</video>')

**Comment by techbliss** [comment]
ok license it fixed

**Comment by techbliss** [comment]
ok license it fixed
