### ISSUE TITLE
Can you support cooler for nest thermostate 

### ISSUE THREAD

**Issue by Kimhy75** [GuillaumeWaignier/fibaro#3]
Hello

Can you support cooler for nest thermostate ?

Thanks.

**Comment by GuillaumeWaignier** [comment]
Hello

I have not the device with cooler, so I will be unable to perform any test.

In this version, the available modes are hardcoded (Off, Heat, Eco).
I can first retrieve the available modes from the Google API.

Then, if you can provide the response of the API (with a cooler device), I will be able to implement the cooler feature.
You can do this by uncommented the debug log:

```lua
function NestThermostat:updateDevice(body)
    --self:debug("updateDevice " .. self.id .. " with body " .. json.encode(body))
```

You will have a response like this in the log:
> Do not send the field that contains private information, that contains  **"enterprises/XYZ/..."**

```json
{
  "devices": [
   {
      "name": "enterprises/XYZ/devices/123",
      "type": "THERMOSTAT",
      "assignee": "enterprises/XYZ/structures/ABC/rooms/123",
      "traits": {
           "sdm.devices.traits.ThermostatMode" : {
               "availableModes" : ["HEAT",  "OFF"],
               "mode" : "HEAT"
           },
           "sdm.devices.traits.ThermostatTemperatureSetpoint" : {
             "heatCelsius" : 20.0,
           }
      },
      "parentRelations": [
        {
           "parent": "enterprises/XYZ/structures/ABC",
           "displayName": ""
        }
      ]
    } 
  ]
}
```

Thanks

**Comment by GuillaumeWaignier** [comment]
Hello,

The version 1.1.0 add the support for cooler.

Regards,

**Comment by Sjekke** [comment]
Boiler support?

**Comment by GuillaumeWaignier** [comment]
The version 1.1.0 of the quickApp integrate all functionalities provided by the Google Nest API:
* heating (such as gas boiler)
* cooling (such as air conditioner)
* switch mode (heat, off, eco, cool, auto)
* set/get temperature set point
* display if the boiler/cooler is actually heating/cooling
* get the ambiant temperature and humidity

These following functionalities can not be supported since Google do not provide any API on these features:
* water heater
* configure eco temperature

**Comment by Sjekke** [comment]
Thx for the feedback!

**Comment by peterv959** [comment]
I had no luck connecting my Z-Box hub over this past weekend. But when I
saw a new version yesterday, I tried again and it worked perfectly. Not
positive about whether it was the new version or if I did something right.
I want to build on your work to get my Chamberlain garage door working.
Probably not until Friday but I hope that's alright with you. I will give
you full credit for your work..

Thank you.

Peter R Vermilye

**Comment by GuillaumeWaignier** [comment]
In version 1.1.0, I modified the line where the quickApp crashes with the Z-Box hub (the problem was presented in https://marketplace.fibaro.com/items/nest-thermostat).
There was a possibility that this could solve the problem.

**Comment by peterv959** [comment]
Thanks for that info. I have a few more issues but I haven't put issues on
Github before. I am based in the US where we use Fahrenheit. I see that the
setpoint traits are in Celsius but the trace message shows my settings with
the number in the units I entered. Everything is displaying in Fahrenheit.
I was poking around trying to see how to determine what units are being
used with my goal being to convert to Celsius when updating the Nest API. I
also see that one of the setpoints is not being rounded.

I am at work on my phone so the screens are a bit funky but I am attaching
screenshots just the same. Hope this helps.

Peter
