### ISSUE TITLE
Curl request fails to get an access token and a refresh token.

### ISSUE THREAD

**Issue by StephanvP** [GuillaumeWaignier/fibaro#5]
Hi, thanks for all the good work. I'm getting an error when trying the curl:

I replaced oauth2-client-id, oauth2-client-secret and authorization-code 
FIrst I get error:

curl: (3) URL using bad/illegal format or missing URL

I googled and found out, I have to replace the single: '  with : "

curl -L -X POST "https://www.googleapis.com/oauth2/v4/token?client_id=CLIENID&client_secret=CLIENTSECRET&code=AUTHORIZATIONCODE&grant_type=authorization_code&redirect_uri=https://www.google.com"

Now I get error:
Error 411 (Length Required)!!1

How can I solve this? AM I doing something wrong?

Thanks in advance and Kind Regards,
Stephan

**Comment by GuillaumeWaignier** [comment]
Hi,

The Nest plugin autommatically get the token. So you do not need to do this curl request.

You only need to add the clientId, clientSecret, AuthorizationCode in the quickApp parameters:
https://github.com/GuillaumeWaignier/fibaro/tree/master/quickApp/Nest#detailled-installation-guide
