### ISSUE TITLE
Incomplete support for Fahrenheit units

### ISSUE THREAD

**Issue by peterv959** [GuillaumeWaignier/fibaro#6]
I have gotten this QuickApp running on my Z-Box hub. I have found a few problems with the updating of the Auto Setpoints. While watching the console, I notice that if I change the heating setpoint, the value that is sent to the API is the Fahrenheit number of degrees. However, the docs for the API indicate that the setpoints must be sent in Celsius number of degrees. So when I change the heat, I see a heat setpoint being sent of 70 and a cooling setpoint of 22. Likewise, it tries to send the cooling setpoint in Fahrenheit and the heating setpoint in Celsius.

I have made a few changes to my code and would like to offer it for an update. There was one other typo dealing with the wrong class (I think). There was a QuickApp:updateDevice where there should have been a NestThermostatTemperature:updateDevice.

I have not done this before so I hope I can submit it properly.

Peter

**Comment by GuillaumeWaignier** [comment]
Hi,

Thanks for your contribution.
I tested with my Home Center 3 (with celcius and fahrenheit configuration) and I have make some modifications.

Let me know if it still works for you.

* On my side, I have not the scale parameter. So I used the unit configuration.
* When I set my box with fahrenheit, *self.properties.coolingThermostatSetpoint* is in fahrenheit with auto mode. So I converted to celcius degrees (line [215]( https://github.com/GuillaumeWaignier/fibaro/blob/master/quickApp/Nest/thermostat.lua#L215))
* The same with *self.properties.heatingThermostatSetpoint* (line [240]( https://github.com/GuillaumeWaignier/fibaro/blob/master/quickApp/Nest/thermostat.lua#L240))

Thanks,

**Comment by peterv959** [comment]
I will look at it on Friday (unless the ice storm hits tonight and the city
shuts down. A real possibility here in Memphis, Tennessee, USA. Thank you
for this QA. I learned a lot from it.


Peter

**Comment by peterv959** [comment]
This is the screen I saw that indicated the Setpoint must be in Celsius. They don’t emphasize that very well. On a different, but related note, how do the setSetpoint methods get wired up to be called by the UI? I am investigating that. Seems to me that if you could rewire that whenever the mode is changed it would ease the updating of both setpoints in Auto/HEATCOOL mode. That is a piece of the puzzle I haven’t found yet. Peter

**Comment by GuillaumeWaignier** [comment]
The screenshot does not work with mail. You need to use the Web interface and import the file.
