### ISSUE TITLE
Access Blocked: This app's request is invalid

### ISSUE THREAD

**Issue by LodeBo** [GuillaumeWaignier/fibaro#8]
Hi,
Many thanks for providing the Quickapp.
I folllowed all the steps and it looks ok but i get this error just before i should get the authorization code.

Access Blocked: This app's request is invalid.
You can't log in because this app sent an invalid request. 
Please try again later or contact the developer about this issue.

Can you take a look at this please ?
Thanks.

**Comment by LodeBo** [comment]
Found it. Restarted my pc and logged in again.
Strange anyway……
Many thanks again for your fantastic QuickApp.
😉

**Comment by GuillaumeWaignier** [comment]
Hi,

Perfect. If it works for you, I'll close this issue in a few days.
